[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
solc-optimizer = true
solc-optimizer-runs = 99999
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/"
    ]


[profile.default.ir]
enabled = true

[rpc_endpoints]
polygon-mumbai = "${POLYGON_MUMBAI_RPC}"
polygon-zkevm = "${POLYGON_ZKEVM_TESTNET_RPC}"
scroll-sepolia = "${SCROLL_SEPOLIA_RPC}"
mantle-testnet = "${MANTLE_TESTNET_RPC}"
sepolia = "${SEPOLIA_RPC}"

[etherscan]
polygon-mumbai = { key = "${POLYGON_ETHERSCAN_API_KEY}", url = "https://api-testnet.polygonscan.com/api" }
polygon-zkevm = { key = "${POLYGON_ZKEVM_ETHERSCAN_API_KEY}", url = "https://api-testnet-zkevm.polygonscan.com/api" }
scroll-sepolia = { key = "${SCROLL_SEPOLIA_ETHERSCAN_API_KEY}", url = "https://api-sepolia.scrollscan.com/api" }
mantle-testnet = { key = "${MANTLE_TESTNET_API_KEY}", url = "https://explorer.testnet.mantle.xyz/api " }
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }